// Core
import type { Metadata } from "next";
import { PrimeReactProvider } from 'primereact/api';

// Styles
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import "./globals.css";
import styles from "./layout.module.css"

// Organisms
import Navbar from "./organisms/navbar/navbar";
import Aside from "./organisms/aside/aside";

//TODO: Agregar meta data y pasar a utils
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
      <PrimeReactProvider>
        <Navbar />
        <div className={styles['content-wrapper']}>
          <Aside />
          <main>{children}</main>
        </div>
      </PrimeReactProvider>
      </body>
    </html>
  );
}
