import type { Metadata } from "next";

import 'primereact/resources/themes/saga-blue/theme.css';  // Puedes elegir otro tema
import 'primereact/resources/primereact.min.css';          // Estilos de PrimeReact
import 'primeicons/primeicons.css';                        // Iconos de PrimeReact
import 'primeflex/primeflex.css';                          // Estilos de PrimeFlex
import "./globals.css";

import Navbar from "./components/navbar/navbar";
import Sidebar from "./components/aside/aside";
import styles from "./layout.module.css"


import { PrimeReactProvider } from 'primereact/api';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
      <PrimeReactProvider>
        <Navbar />
        <div className={styles['content-wrapper']}>
          <Sidebar />
          <main>{children}</main>
        </div>
      </PrimeReactProvider>
      </body>
    </html>
  );
}
